//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly_Project_iRely.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoviesRentalDbEntities : DbContext
    {
        public MoviesRentalDbEntities()
            : base("name=MoviesRentalDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<movieReg> movieRegs { get; set; }
        public virtual DbSet<rent> rents { get; set; }
        public virtual DbSet<returnmovie> returnmovies { get; set; }
    }
}
