//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly_Project_iRely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rent
    {
        public int id { get; set; }
        public string movieid { get; set; }
        public string customername { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<int> fee { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
    }
}
